# Generated by Django 5.0.3 on 2024-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('program', models.CharField(choices=[('mbbs', 'MBBS'), ('md', 'MD')], default='MBBS', max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=3)),
            ],
        ),
    ]
